service:
  name: hello-serverless-xray-typescript

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-northeast-2
  tracing:
    apiGateway: true
    lambda: true

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
